# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  - darwin
dockers:
- image_templates:
  - "caarlos0/openvpn-exporter:latest"
  - "caarlos0/openvpn-exporter:{{ .Tag }}"
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{ .Version }}"
  - "--label=org.label-schema.name={{ .ProjectName }}"
